Develop
tdeshong/bikeshareAvailability pull request #1
Opened 2020-01-26 19:19 UTC by tdeshong

Kafka producer.py with the bash script to spawn the stream
stream.py (using spark streams)

2020-02-07 09:21 UTC, tdeshong commented
flask app added and current version of kafka and spark streaming

2020-02-13 00:07 UTC, coruscating requested changes

2020-02-13 00:07 UTC, coruscating commented on README.md
> +# Bikeshare Availability
finish readme

2020-02-13 00:07 UTC, coruscating commented on flask/database.py
> +    conn = psycopg2.connect("host= ec2-18-210-209-145.compute-1.amazonaws.com dbname=bikeshare user=ubuntu password=123")
remove IP and user/password

2020-02-13 02:46 UTC, merged